<?php

/**
 * @file
 * Primary module hooks for helfi_media_formtool module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function helfi_media_formtool_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {

  if ($entity_type->id() === 'media' && $bundle === 'hel_remote_webform') {
    if (isset($fields['field_media_hel_remote_webform'])) {
      $fields['field_media_hel_remote_webform']->addConstraint('ValidMediaFormLink', []);
    }
  }
}
/**
 * Implements hook_theme().
 */
function helfi_media_formtool_theme() {
  return array(
    'form_tool_embedded' => array(
      'variables' => array('url' => NULL),
      'template' => 'form-tool-embed',
    ),
  );
}
